site_name: CodeFeedr
theme:
  name: null
  custom_dir: 'docs/theme'
theme_dir: 'docs/theme'
repo_name: 'joskuijpers/bep_codefeedr'
repo_url: 'https://github.com/joskuijpers/bep_codefeedr'
pages:
- Home: 'index.md'
- Getting Started: 'getting_started.md'
- Core:
  - 'Pipeline': 'core/pipeline.md'
  - 'Buffers': 'core/buffers.md'
  - 'Key Management':
    - 'Key Manager': 'core/key-manager.md'
    - 'redis': 'core/redis-key-manager.md'
    - 'mongoDB': 'core/mongo-key-manager.md'
- Plugins:
  - 'GitHub': 'plugins/plugin-examples.md'
  - 'RSS': 'plugins/plugin-examples.md'
  - 'Apache Access Logs': 'plugins/plugin-examples.md'
  - 'Historic data': 'plugins/historic-data.md'
