version: '3.4'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    hostname: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    links:
      - elasticsearch

    ports:
      - 5601:5601

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: "single-node"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

volumes:
  esdata1:
    driver: local
